package com.xderhuo.domain;

import javax.persistence.Id;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    @Id
    private String bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_info
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    private String bookInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.number
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookid
     *
     * @return the value of book.bookid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public String getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookid
     *
     * @param bookid the value for book.bookid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public void setBookid(String bookid) {
        this.bookid = bookid == null ? null : bookid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_info
     *
     * @return the value of book.book_info
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public String getBookInfo() {
        return bookInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_info
     *
     * @param bookInfo the value for book.book_info
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public void setBookInfo(String bookInfo) {
        this.bookInfo = bookInfo == null ? null : bookInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.number
     *
     * @return the value of book.number
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.number
     *
     * @param number the value for book.number
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}