package domain;

import java.util.Date;

public class Appoin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appoin.aid
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appoin.a_uname
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    private String aUname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appoin.a_phone
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    private String aPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appoin.a_carid
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    private String aCarid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appoin.a_carname
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    private String aCarname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appoin.a_carprice
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    private Integer aCarprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appoin.a_service
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    private String aService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appoin.a_starttime
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    private Date aStarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appoin.apo_time
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    private Date apoTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appoin.a_static
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    private String aStatic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appoin.dsc
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    private String dsc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appoin.aid
     *
     * @return the value of appoin.aid
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appoin.aid
     *
     * @param aid the value for appoin.aid
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appoin.a_uname
     *
     * @return the value of appoin.a_uname
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public String getaUname() {
        return aUname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appoin.a_uname
     *
     * @param aUname the value for appoin.a_uname
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public void setaUname(String aUname) {
        this.aUname = aUname == null ? null : aUname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appoin.a_phone
     *
     * @return the value of appoin.a_phone
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public String getaPhone() {
        return aPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appoin.a_phone
     *
     * @param aPhone the value for appoin.a_phone
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public void setaPhone(String aPhone) {
        this.aPhone = aPhone == null ? null : aPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appoin.a_carid
     *
     * @return the value of appoin.a_carid
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public String getaCarid() {
        return aCarid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appoin.a_carid
     *
     * @param aCarid the value for appoin.a_carid
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public void setaCarid(String aCarid) {
        this.aCarid = aCarid == null ? null : aCarid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appoin.a_carname
     *
     * @return the value of appoin.a_carname
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public String getaCarname() {
        return aCarname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appoin.a_carname
     *
     * @param aCarname the value for appoin.a_carname
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public void setaCarname(String aCarname) {
        this.aCarname = aCarname == null ? null : aCarname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appoin.a_carprice
     *
     * @return the value of appoin.a_carprice
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public Integer getaCarprice() {
        return aCarprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appoin.a_carprice
     *
     * @param aCarprice the value for appoin.a_carprice
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public void setaCarprice(Integer aCarprice) {
        this.aCarprice = aCarprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appoin.a_service
     *
     * @return the value of appoin.a_service
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public String getaService() {
        return aService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appoin.a_service
     *
     * @param aService the value for appoin.a_service
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public void setaService(String aService) {
        this.aService = aService == null ? null : aService.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appoin.a_starttime
     *
     * @return the value of appoin.a_starttime
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public Date getaStarttime() {
        return aStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appoin.a_starttime
     *
     * @param aStarttime the value for appoin.a_starttime
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public void setaStarttime(Date aStarttime) {
        this.aStarttime = aStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appoin.apo_time
     *
     * @return the value of appoin.apo_time
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public Date getApoTime() {
        return apoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appoin.apo_time
     *
     * @param apoTime the value for appoin.apo_time
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public void setApoTime(Date apoTime) {
        this.apoTime = apoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appoin.a_static
     *
     * @return the value of appoin.a_static
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public String getaStatic() {
        return aStatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appoin.a_static
     *
     * @param aStatic the value for appoin.a_static
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public void setaStatic(String aStatic) {
        this.aStatic = aStatic == null ? null : aStatic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appoin.dsc
     *
     * @return the value of appoin.dsc
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public String getDsc() {
        return dsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appoin.dsc
     *
     * @param dsc the value for appoin.dsc
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    public void setDsc(String dsc) {
        this.dsc = dsc == null ? null : dsc.trim();
    }
}