package mapper;

import domain.Appoin;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface AppoinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appoin
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    @Delete({
        "delete from appoin",
        "where aid = #{aid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appoin
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    @Insert({
        "insert into appoin (aid, a_uname, ",
        "a_phone, a_carid, ",
        "a_carname, a_carprice, ",
        "a_service, a_starttime, ",
        "apo_time, a_static, dsc)",
        "values (#{aid,jdbcType=INTEGER}, #{aUname,jdbcType=VARCHAR}, ",
        "#{aPhone,jdbcType=VARCHAR}, #{aCarid,jdbcType=VARCHAR}, ",
        "#{aCarname,jdbcType=VARCHAR}, #{aCarprice,jdbcType=INTEGER}, ",
        "#{aService,jdbcType=VARCHAR}, #{aStarttime,jdbcType=DATE}, ",
        "#{apoTime,jdbcType=DATE}, #{aStatic,jdbcType=VARCHAR}, #{dsc,jdbcType=VARCHAR})"
    })
    int insert(Appoin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appoin
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    @Select({
        "select",
        "aid, a_uname, a_phone, a_carid, a_carname, a_carprice, a_service, a_starttime, ",
        "apo_time, a_static, dsc",
        "from appoin",
        "where aid = #{aid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="aid", property="aid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="a_uname", property="aUname", jdbcType=JdbcType.VARCHAR),
        @Result(column="a_phone", property="aPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="a_carid", property="aCarid", jdbcType=JdbcType.VARCHAR),
        @Result(column="a_carname", property="aCarname", jdbcType=JdbcType.VARCHAR),
        @Result(column="a_carprice", property="aCarprice", jdbcType=JdbcType.INTEGER),
        @Result(column="a_service", property="aService", jdbcType=JdbcType.VARCHAR),
        @Result(column="a_starttime", property="aStarttime", jdbcType=JdbcType.DATE),
        @Result(column="apo_time", property="apoTime", jdbcType=JdbcType.DATE),
        @Result(column="a_static", property="aStatic", jdbcType=JdbcType.VARCHAR),
        @Result(column="dsc", property="dsc", jdbcType=JdbcType.VARCHAR)
    })
    Appoin selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appoin
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    @Select({
        "select",
        "aid, a_uname, a_phone, a_carid, a_carname, a_carprice, a_service, a_starttime, ",
        "apo_time, a_static, dsc",
        "from appoin",
        "order by age desc,username asc"
    })
    @Results({
        @Result(column="aid", property="aid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="a_uname", property="aUname", jdbcType=JdbcType.VARCHAR),
        @Result(column="a_phone", property="aPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="a_carid", property="aCarid", jdbcType=JdbcType.VARCHAR),
        @Result(column="a_carname", property="aCarname", jdbcType=JdbcType.VARCHAR),
        @Result(column="a_carprice", property="aCarprice", jdbcType=JdbcType.INTEGER),
        @Result(column="a_service", property="aService", jdbcType=JdbcType.VARCHAR),
        @Result(column="a_starttime", property="aStarttime", jdbcType=JdbcType.DATE),
        @Result(column="apo_time", property="apoTime", jdbcType=JdbcType.DATE),
        @Result(column="a_static", property="aStatic", jdbcType=JdbcType.VARCHAR),
        @Result(column="dsc", property="dsc", jdbcType=JdbcType.VARCHAR)
    })
    List<Appoin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appoin
     *
     * @mbg.generated Mon May 21 17:26:54 CST 2018
     */
    @Update({
        "update appoin",
        "set a_uname = #{aUname,jdbcType=VARCHAR},",
          "a_phone = #{aPhone,jdbcType=VARCHAR},",
          "a_carid = #{aCarid,jdbcType=VARCHAR},",
          "a_carname = #{aCarname,jdbcType=VARCHAR},",
          "a_carprice = #{aCarprice,jdbcType=INTEGER},",
          "a_service = #{aService,jdbcType=VARCHAR},",
          "a_starttime = #{aStarttime,jdbcType=DATE},",
          "apo_time = #{apoTime,jdbcType=DATE},",
          "a_static = #{aStatic,jdbcType=VARCHAR},",
          "dsc = #{dsc,jdbcType=VARCHAR}",
        "where aid = #{aid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Appoin record);
}