package com.xderhuo.mapper;

import com.xderhuo.domain.Grade;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import tk.mybatis.mapper.common.Mapper;

import java.util.List;

public interface GradeMapper extends Mapper<Grade> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Fri May 25 12:06:03 CST 2018
     */
    @Delete({
        "delete from grade",
        "where cid = #{cid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Fri May 25 12:06:03 CST 2018
     */
    @Insert({
        "insert into grade (cid, cname, ",
        "id)",
        "values (#{cid,jdbcType=INTEGER}, #{cname,jdbcType=VARCHAR}, ",
        "#{id,jdbcType=INTEGER})"
    })
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Fri May 25 12:06:03 CST 2018
     */
    @Select({
        "select",
        "cid, cname, id",
        "from grade",
        "where cid = #{cid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="cid", property="cid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="cname", property="cname", jdbcType=JdbcType.VARCHAR),
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER)
    })
    Grade selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Fri May 25 12:06:03 CST 2018
     */
    @Select({
        "select",
        "cid, cname, id",
        "from grade"
    })
    @Results({
        @Result(column="cid", property="cid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="cname", property="cname", jdbcType=JdbcType.VARCHAR),
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER)
    })
    List<Grade> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbg.generated Fri May 25 12:06:03 CST 2018
     */
    @Update({
        "update grade",
        "set cname = #{cname,jdbcType=VARCHAR},",
          "id = #{id,jdbcType=INTEGER}",
        "where cid = #{cid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Grade record);
}