package com.xderhuo.mapper;

import com.xderhuo.domain.School;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface SchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri May 25 12:06:03 CST 2018
     */
    @Delete({
        "delete from school",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri May 25 12:06:03 CST 2018
     */
    @Insert({
        "insert into school (id, sname)",
        "values (#{id,jdbcType=INTEGER}, #{sname,jdbcType=VARCHAR})"
    })
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri May 25 12:06:03 CST 2018
     */
    @Select({
        "select",
        "id, sname",
        "from school",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="sname", property="sname", jdbcType=JdbcType.VARCHAR)
    })
    School selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri May 25 12:06:03 CST 2018
     */
    @Select({
        "select",
        "id, sname",
        "from school"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="sname", property="sname", jdbcType=JdbcType.VARCHAR)
    })
    List<School> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri May 25 12:06:03 CST 2018
     */
    @Update({
        "update school",
        "set sname = #{sname,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(School record);
}