package com.xderhuo.domain;

import java.util.Date;

public class Loan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.lid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    private Integer lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.uid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loanTime
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    private Date loantime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.bookid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    private String bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan.loanNumber
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    private Integer loannumber;

    private Book book ;

    public Book getBook() {
        return book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.lid
     *
     * @return the value of loan.lid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.lid
     *
     * @param lid the value for loan.lid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.uid
     *
     * @return the value of loan.uid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.uid
     *
     * @param uid the value for loan.uid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loanTime
     *
     * @return the value of loan.loanTime
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public Date getLoantime() {
        return loantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loanTime
     *
     * @param loantime the value for loan.loanTime
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public void setLoantime(Date loantime) {
        this.loantime = loantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.bookid
     *
     * @return the value of loan.bookid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public String getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.bookid
     *
     * @param bookid the value for loan.bookid
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public void setBookid(String bookid) {
        this.bookid = bookid == null ? null : bookid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan.loanNumber
     *
     * @return the value of loan.loanNumber
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public Integer getLoannumber() {
        return loannumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan.loanNumber
     *
     * @param loannumber the value for loan.loanNumber
     *
     * @mbg.generated Fri May 25 18:11:55 CST 2018
     */
    public void setLoannumber(Integer loannumber) {
        this.loannumber = loannumber;
    }
}